### ISSUE TITLE
แสดงผังเครือญาติ (Genogram)

### ISSUE THREAD

**Issue by porntipa** [ffc-nectec/android#10]

**Comment by porntipa** [comment]
ใช้ข้อมูลในส่วนของฟิลด์ marrystatus, familyno, familyposition, fatherid,
motherid ในตาราง Person

**Comment by piruin** [comment]
Reference
[![Genogram](https://www.smartdraw.com/genogram/img/genogram-example.jpg?bn=1510011130)](https://www.smartdraw.com/genogram/)
